version: '3'

services:

  sshd-server:
    build:
      context: .
      dockerfile: sshd-server.dockerfile
    volumes:
      - socks-server:/root/.ssh/
  
  socks-server:
    build:
      context: .
      dockerfile: socks-server.dockerfile
    volumes:
      - socks-server:/root/.ssh/
    depends_on:
      - sshd-server
    ports:
      - 1080:1080

volumes:
  socks-server: